name: flutterbuyandsell
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^2.2.3
  http: ^1.2.2
  provider: ^6.1.2
  # connectivity: 3.0.6
  connectivity_plus: ^6.0.5
  theme_manager: ^2.0.4
  flutter_map: ^7.0.2
  cached_network_image: ^3.4.0
  easy_localization: ^3.0.7
  #latlng: 0.1.0
  latlong2: ^0.9.1
  # flutter_map_tappable_polyline: 3.2.0
  image_picker: ^0.8.8+7
  # flutter_widget_from_html: 0.8.1+1
  flutter_html: ^3.0.0-beta.2
  sembast: ^3.7.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.4.0
  firebase_core_platform_interface: ^5.3.1
  firebase_messaging: ^15.1.6
  firebase_database: ^11.1.1
  firebase_auth: ^5.3.4
  #flutter_native_admob: 2.1.0+3 ###
  # google_mobile_ads: ^5.2.0
  # google_mobile_ads : 
  #   git:
  #     url: https://github.com/SuaMusica/googleads-mobile-flutter.git
  #     path: packages/google_mobile_ads
  #     ref: feature/suamusica
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  photo_view: ^0.15.0
  progress_dialog_null_safe: ^3.0.0
  #  flutter_braintree: 2.3.1
  # launch_review: 3.0.1
  # package_info: 2.0.2
  package_info_plus: ^8.0.2
  fluttericon: 2.0.0
  flutter_stripe: ^11.3.0
  # flutter_credit_card: ^4.0.1
  fluttertoast: ^8.2.8
  permission_handler: ^11.3.1
  permission_handler_platform_interface: ^4.2.3
  geolocator: ^13.0.2 # Sticked with 7.6.2 for now. If app support android 12, need to update this lib
  # share: 2.0.4
  share_plus: ^10.0.0
  the_apple_sign_in: 1.1.1
  razorpay_flutter: ^1.3.7
  group_radio_button: ^1.3.0
  # flutter_native_image: 0.0.6+1
  # flutter_paystack: 1.0.5+1
  in_app_purchase: ^3.2.0
  # camera: 0.8.0
  # flutter_better_camera: 1.0.2+1
  flutter_linkify: ^6.0.0
  google_maps_flutter: ^2.6.1
  collection: ^1.18.0
  # file_picker: ^8.1.3
  video_thumbnail: 0.5.3
  # video_thumbnail:
  #   git: https://github.com/ajbcoder/video_thumbnail
  video_player: ^2.9.2
  flutter_svg: ^2.0.10+1
  community_material_icon: 5.9.55
  visibility_detector: ^0.4.0+2
  geocoding: ^3.0.0
  camera: ^0.11.0+2
  app_tracking_transparency: ^2.0.6
  firebase_crashlytics: ^4.2.0
  quiver: ^3.2.2
  pedantic: ^1.11.1
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0
#   xml: '6.1.0'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/placeholder_circle_image.png
  - assets/images/placeholder_image.png
  - assets/langs/ar-DZ.json
  - assets/langs/en-US.json
  - assets/langs/hi-IN.json
  - assets/langs/de-DE.json
  - assets/langs/es-ES.json
  - assets/langs/fr-FR.json
  - assets/langs/id-ID.json
  - assets/langs/it-IT.json
  - assets/langs/ja-JP.json
  - assets/langs/ko-KR.json
  - assets/langs/ms-MY.json
  - assets/langs/pt-PT.json
  - assets/langs/ru-RU.json
  - assets/langs/th-TH.json
  - assets/langs/tr-TR.json
  - assets/langs/zh-CN.json
  - assets/images/verify_email_icon.jpg
  - assets/images/down.png
  - assets/images/baesline_access_time_black_24.png
  - assets/images/baseline_check_green_24.png
  - assets/images/baseline_graph_black_24.png
  - assets/images/baseline_price_down_black_24.png
  - assets/images/chat.png
  - assets/images/seo.png
  - assets/images/upload.png
  - assets/images/baseline_price_up_black_24.png
  - assets/images/baseline_empty_item_grey_24.png
  - assets/images/home_icon/discount_products.png
  - assets/images/home_icon/easy_payment.png
  - assets/images/home_icon/featured_products.png
  - assets/images/home_icon/free_download.png
  - assets/images/trending.png
  - assets/images/flutter_buy_and_sell_logo.png
  - assets/images/flutter_buy_and_sell_logo_light.png
  - assets/images/baseline_pin_black_24.png
  - assets/images/baseline_favourite_grey_24.png
  - assets/images/default_image.png
  - assets/images/baseline_promotion_color_74.png
  - assets/images/user_default_photo.png
  - assets/images/loaction_illustration.svg
  - assets/images/slider_1.svg
  - assets/images/slider_2.svg
  - assets/images/slider_3.svg
  - assets/images/demo_alert.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Product Sans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
    - asset: assets/fonts/Product-Sans-Bold.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
